In [1]:
import numpy as np
import pandas as pd
import googlemaps

In [2]:
crime_anal_police = pd.read_csv('../data/02. crime_in_Seoul_include_gu_name.csv', thousands=',', index_col=0)

In [29]:
crime_anal_police.head()

,구별,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄,검거
0,강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,0.894540,85.463066
1,강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,0.223310,85.550226
2,강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,0.298949,94.070728
3,관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,0.522733,85.212224
4,광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707,0.406888,96.375820

In [30]:
gmaps_key = 'AIzaSyAlx5p8xnr2chNftLcxDdKQfaATFW6momg'
gmaps = googlemaps.Client(key=gmaps_key)
gmaps.geocode('서울중부경찰서', language='ko')

[{'address_components': [{'long_name': '２７',
    'short_name': '２７',
    'types': ['premise']},
   {'long_name': '수표로',
    'short_name': '수표로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '중구',
    'short_name': '중구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '100-032',
    'short_name': '100-032',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 중구 수표로 27',
  'geometry': {'location': {'lat': 37.56361709999999, 'lng': 126.9896517},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.5649660802915,
     'lng': 126.9910006802915},
    'southwest': {'lat': 37.5622681197085, 'lng': 126.9883027197085}}},
  'partial_match': True,
  'place_id': 'ChIJc-9q5uSifDURLhQmr5wkXmc',
  'plus_code': {'compound_code': 'HX7Q+CV 대한민국 서울특별시',
   'global_code': '8Q98HX7Q+CV'},
  'types': ['establishment', 'point_of_interest', 'police']}]

In [31]:
tmp = gmaps.geocode('서울중부경찰서', language='ko')
print (tmp[0].get('formatted_address'))
#print (tmp[0].get('geometry'))
tmp_loc = tmp[0].get('geometry')
print ('위도 : ', tmp_loc['location']['lat'])
print ('경도 : ', tmp_loc['location']['lng'])

대한민국 서울특별시 중구 수표로 27
위도 :  37.56361709999999
경도 :  126.9896517

In [53]:
station_name = []

for name in crime_anal_police['관서명']:
    station_name.append('서울' + str(name[:-1]) + '경찰서')

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [54]:
station_address = []
station_lat = []
station_lng = []

for name in station_name:
    tmp = gmaps.geocode(name, language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    station_lat.append(tmp[0].get('geometry')['location']['lat'])
    station_lng.append(tmp[0].get('geometry')['location']['lng'])
# print (station_address)
# print (station_lat)
# print(station_lng)

['대한민국 서울특별시 중구 수표로 27', '대한민국 서울특별시 종로구 율곡로 46', '대한민국 서울특별시 중구 한강대로 410', '대한민국 서울특별시 서대문구 통일로 113', '대한민국 서울특별시 종로구 창경궁로 112-16', '대한민국 서울특별시 용산구 백범로 329', '대한민국 서울특별시 성북구 삼선동 보문로 170', '대한민국 서울특별시 동대문구 약령시로21길 29', '대한민국 서울특별시 마포구 마포대로 183', '대한민국 서울특별시 영등포구 국회대로 608', '대한민국 서울특별시 성동구 행당동 왕십리광장로 9', '대한민국 서울특별시 동작구 노량진로 148', '대한민국 서울특별시 광진구 구의동 자양로 167', '대한민국 서울특별시 은평구 녹번동 177-15', '대한민국 서울특별시 강북구 오패산로 406', '대한민국 서울특별시 금천구 시흥대로73길 50', '대한민국 서울특별시 중랑구 묵2동 249-2', '대한민국 서울특별시 강남구 테헤란로114길 11', '대한민국 서울특별시 관악구 관악로5길 33', '대한민국 서울특별시 강서구 화곡6동 980-27', '대한민국 서울특별시 강동구 성내로 57', '대한민국 서울특별시 성북구 화랑로7길 32', '대한민국 서울특별시 구로구 가마산로 235', '대한민국 서울특별시 서초구 서초3동 반포대로 179', '대한민국 서울특별시 양천구 목동동로 99', '대한민국 서울특별시 송파구 중대로 221', '대한민국 서울특별시 노원구 노원로 283', '대한민국 서울특별시 서초구 동작대로 204', '대한민국 서울특별시 은평구 연서로 365', '대한민국 서울특별시 도봉구 노해로 403', '대한민국 서울특별시 강남구 개포로 617']
[37.56361709999999, 37.575548, 37.5547584, 37.5647439, 37.5719679, 37.5387099, 37.58977830000001, 37.58506149999999, 37.550814, 37.5260441, 37.5617303, 37.5130866, 37.542873, 37.6021405, 37.63730390000001, 37.4568722, 37.6056429, 37.5094352, 37.4743945, 37.551284, 37.528511, 37.6036426, 37.494931, 37.4956054, 37.5167711, 37.5016941, 37.6421389, 37.4945959, 37.6280204, 37.6533589, 37.49349]
[126.9896517, 126.9847471, 126.9734981, 126.9667705, 126.9989574, 126.9659183, 127.016589, 127.0457679, 126.954028, 126.9008091, 127.0364217, 126.9428498, 127.083821, 126.9213074, 127.0273399, 126.8970429, 127.0764866, 127.0669578, 126.9513489, 126.850038, 127.1268224, 127.0401328, 126.886731, 127.0052504, 126.8656996, 127.1272481, 127.0710473, 126.9831279, 126.9287899, 127.052682, 127.0772119]

In [55]:
gu_name = []
for name in station_address:
    tmp = name.split()
    tmp_gu = [gu for gu in tmp if gu[-1] == '구'][0]
    gu_name.append(tmp_gu)

crime_anal_police['구별'] = gu_name
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [56]:
crime_anal_police.to_csv('../output/02_crime_in_Seoul_include_gu_name.csv', sep=',', encoding='utf-8')

In [3]:
crime_anal_police.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 0 to 30
Data columns (total 12 columns):
관서명      31 non-null object
살인 발생    31 non-null int64
살인 검거    31 non-null int64
강도 발생    31 non-null int64
강도 검거    31 non-null int64
강간 발생    31 non-null int64
강간 검거    31 non-null int64
절도 발생    31 non-null int64
절도 검거    31 non-null int64
폭력 발생    31 non-null int64
폭력 검거    31 non-null int64
구별       31 non-null object
dtypes: int64(10), object(2)
memory usage: 3.1+ KB

In [2]:
crime_anal_raw = pd.read_csv('../output/02_crime_in_Seoul_include_gu_name.csv', encoding='utf-8', index_col=0)
crime_anal = pd.pivot_table(crime_anal_raw, index='구별', aggfunc=sum)
# crime_anal_raw.head()
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
강서구    191    262     13     13      8      7   1260   2096   2718   3207
관악구    221    320     14     12      8      9    827   2706   2642   3298

In [3]:
lists = ['강간', '강도', '살인', '절도', '폭력']
for st in lists:
    crime_anal[st+'검거율'] = crime_anal[st+' 검거']/crime_anal[st+' 발생']*100
    del crime_anal[st + ' 검거']

In [5]:
con_list = ['강간검거율', '강도검거율', '살인검거율', '절도검거율', '폭력검거율']
for column in con_list:
    crime_anal.loc[crime_anal[column] > 100, column] = 100
crime_anal.head()
for st in lists:
    crime_anal.rename(columns = {st+' 발생':st}, inplace=True)

In [8]:
from sklearn import preprocessing
col = ['강간', '강도', '살인', '절도', '폭력']
col2 = ['강간검거율', '강도검거율', '살인검거율', '절도검거율', '폭력검거율']

x = crime_anal[col].values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x.astype(float))

crime_anal_norm = pd.DataFrame(x_scaled, columns = col, index=crime_anal.index)
crime_anal_norm[col2] = crime_anal[col2]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,1.000000,1.000000,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.467528,0.437969,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.133118,0.415445,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,0.461095,0.470588,0.416667,0.370649,0.614945,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,0.628242,0.411765,0.583333,0.589523,0.647479,69.062500,100.000000,88.888889,30.561715,80.109157

In [9]:
crime_anal_norm.to_csv('../output/02_0721_normalized.csv', encoding='utf-8')

In [12]:
result_CCTV = pd.read_csv('../data/01. CCTV_result.csv', encoding='utf-8', index_col='구별')
crime_anal_norm[['인구수', 'CCTV']] = result_CCTV[['인구수', '소계']]
crime_anal_norm['범죄'] = np.sum(crime_anal_norm[col], axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄
구별,,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,1.000000,1.000000,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,4.857843
강동구,0.155620,0.058824,0.166667,0.467528,0.437969,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,1.286607
강북구,0.146974,0.529412,0.416667,0.133118,0.415445,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,1.641616
강서구,0.461095,0.470588,0.416667,0.370649,0.614945,72.900763,100.000000,100.000000,60.114504,84.752105,603772.0,884,2.333944
관악구,0.628242,0.411765,0.583333,0.589523,0.647479,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,2.860342